// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace AmvReporting.Controllers
{
    public partial class ReportRevisionsController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ReportRevisionsController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ViewAllVersions()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewAllVersions);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ViewRevision()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewRevision);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CompareToLatest()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CompareToLatest);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ReportRevisionsController Actions { get { return MVC.ReportRevisions; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "ReportRevisions";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "ReportRevisions";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string ViewAllVersions = "ViewAllVersions";
            public readonly string ViewRevision = "ViewRevision";
            public readonly string CompareToLatest = "CompareToLatest";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string ViewAllVersions = "ViewAllVersions";
            public const string ViewRevision = "ViewRevision";
            public const string CompareToLatest = "CompareToLatest";
        }


        static readonly ActionParamsClass_ViewAllVersions s_params_ViewAllVersions = new ActionParamsClass_ViewAllVersions();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ViewAllVersions ViewAllVersionsParams { get { return s_params_ViewAllVersions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ViewAllVersions
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ViewRevision s_params_ViewRevision = new ActionParamsClass_ViewRevision();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ViewRevision ViewRevisionParams { get { return s_params_ViewRevision; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ViewRevision
        {
            public readonly string id = "id";
            public readonly string revisionNumber = "revisionNumber";
        }
        static readonly ActionParamsClass_CompareToLatest s_params_CompareToLatest = new ActionParamsClass_CompareToLatest();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CompareToLatest CompareToLatestParams { get { return s_params_CompareToLatest; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CompareToLatest
        {
            public readonly string id = "id";
            public readonly string revisiontNumber = "revisionNumber";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _ViewStart = "_ViewStart";
                public readonly string CompareToLatest = "CompareToLatest";
                public readonly string ViewAllVersions = "ViewAllVersions";
                public readonly string ViewRevision = "ViewRevision";
            }
            public readonly string _ViewStart = "~/Views/ReportRevisions/_ViewStart.cshtml";
            public readonly string CompareToLatest = "~/Views/ReportRevisions/CompareToLatest.cshtml";
            public readonly string ViewAllVersions = "~/Views/ReportRevisions/ViewAllVersions.cshtml";
            public readonly string ViewRevision = "~/Views/ReportRevisions/ViewRevision.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ReportRevisionsController : AmvReporting.Controllers.ReportRevisionsController
    {
        public T4MVC_ReportRevisionsController() : base(Dummy.Instance) { }

        [NonAction]
        partial void ViewAllVersionsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ViewAllVersions(System.Guid id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewAllVersions);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ViewAllVersionsOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ViewRevisionOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid id, int revisionNumber);

        [NonAction]
        public override System.Web.Mvc.ActionResult ViewRevision(System.Guid id, int revisionNumber)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewRevision);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "revisionNumber", revisionNumber);
            ViewRevisionOverride(callInfo, id, revisionNumber);
            return callInfo;
        }

        [NonAction]
        partial void CompareToLatestOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid id, int revisiontNumber);

        [NonAction]
        public override System.Web.Mvc.ActionResult CompareToLatest(System.Guid id, int revisionNumber)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CompareToLatest);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "revisionNumber", revisionNumber);
            CompareToLatestOverride(callInfo, id, revisionNumber);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
